In [1]:
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt

# Load your CSV file
df = pd.read_csv('movies.csv')

### Data Inspection

In [2]:
df.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [3]:
df.tail()

,movieId,title,genres
9737,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy
9738,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy
9739,193585,Flint (2017),Drama
9740,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation
9741,193609,Andrew Dice Clay: Dice Rules (1991),Comedy

In [4]:
df.columns

Index(['movieId', 'title', 'genres'], dtype='str')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  9742 non-null   int64
 1   title    9742 non-null   str
 2   genres   9742 non-null   str
dtypes: int64(1), str(2)
memory usage: 228.5 KB

In [6]:
df.describe()

             movieId
count    9742.000000
mean    42200.353623
std     52160.494854
min         1.000000
25%      3248.250000
50%      7300.000000
75%     76232.000000
max    193609.000000

In [7]:
df.isnull().sum()

movieId    0
title      0
genres     0
dtype: int64

### Data Cleaning

In [8]:
df['year'] = df['title'].str.extract(r'\((\d{4})\)')
df['title'] = df['title'].str.replace(r'\s*\(\d{4}\)', '', regex=True)
df.head()

,movieId,title,genres,year
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995
1,2,Jumanji,Adventure|Children|Fantasy,1995
2,3,Grumpier Old Men,Comedy|Romance,1995
3,4,Waiting to Exhale,Comedy|Drama|Romance,1995
4,5,Father of the Bride Part II,Comedy,1995

In [9]:
df.to_csv("movies_cleaned.csv", index=False)

In [10]:
df.head()

,movieId,title,genres,year
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995
1,2,Jumanji,Adventure|Children|Fantasy,1995
2,3,Grumpier Old Men,Comedy|Romance,1995
3,4,Waiting to Exhale,Comedy|Drama|Romance,1995
4,5,Father of the Bride Part II,Comedy,1995

In [11]:
df.tail()

,movieId,title,genres,year
9737,193581,Black Butler: Book of the Atlantic,Action|Animation|Comedy|Fantasy,2017
9738,193583,No Game No Life: Zero,Animation|Comedy|Fantasy,2017
9739,193585,Flint,Drama,2017
9740,193587,Bungo Stray Dogs: Dead Apple,Action|Animation,2018
9741,193609,Andrew Dice Clay: Dice Rules,Comedy,1991

In [12]:
df['year'].isnull().sum()

np.int64(13)

In [13]:
df[df['year'].isnull()][['movieId', 'title']]

      movieId                                              title
6059    40697                                          Babylon 5
9031   140956                                   Ready Player One
9091   143410                                         Hyena Road
9138   147250  The Adventures of Sherlock Holmes and Doctor W...
9179   149334                                  Nocturnal Animals
9259   156605                                           Paterson
9367   162414                                          Moonlight
9448   167570                                             The OA
9514   171495                                             Cosmos
9515   171631                            Maria Bamford: Old Baby
9518   171749                  Death Note: Desu nôto (2006–2007)
9525   171891                                  Generation Iron 2
9611   176601                                       Black Mirror

In [17]:
df.loc[df['movieId'] == 40697, 'year'] = "1994"   # Babylon 5
df.loc[df['movieId'] == 140956, 'year'] = "2018"  # Ready Player One
df.loc[df['movieId'] == 143410, 'year'] = "2015"  # Hyena Road
df.loc[df['movieId'] == 147250, 'year'] = "1980"  # The Adventures of Sherlock Holmes and Dr. Watson
df.loc[df['movieId'] == 149334, 'year'] = "2016"  # Nocturnal Animals
df.loc[df['movieId'] == 156605, 'year'] = "2016"  # Paterson
df.loc[df['movieId'] == 162414, 'year'] = "2016"  # Moonlight
df.loc[df['movieId'] == 167570, 'year'] = "2016"  # The OA
df.loc[df['movieId'] == 171495, 'year'] = "2014"  # Cosmos
df.loc[df['movieId'] == 171631, 'year'] = "2017"  # Maria Bamford: Old Baby
df.loc[df['movieId'] == 171749, 'year'] = "2006"  # Death Note
df.loc[df['movieId'] == 171891, 'year'] = "2017"  # Generation Iron 2
df.loc[df['movieId'] == 176601, 'year'] = "2011"  # Black Mirror

In [18]:
df['year'].isnull().sum()

np.int64(0)

In [19]:
df['year'] = df['year'].astype(int)

In [20]:
df.to_csv("movies_cleaned.csv", index=False)